### PR TITLE
Optimize Queue.summary query #38

### PR DESCRIPTION
**Pull request by thomasmodeneis**

### CODE REVIEW

**Comment by grantcarthew** [comment]
Looks good @thomasmodeneis 
Can you do a `git checkout origin/master tests/test-current.js` and push to prevent the conflict?

**Comment by grantcarthew** [comment]
Looks good @thomasmodeneis. Can you fix the conflict?
Pull the master branch and then do a `git checkout origin/master tests/test-current.js`
This is a good reason to not use the `test-current.js` file for single module testing.

**Comment by thomasmodeneis** [comment]
Just did it, sorry for the delay! :)
Have a great weekend.
Cheers.

**Comment by grantcarthew** [comment]
This is fantastic work @thomasmodeneis

**Comment by thomasmodeneis** [comment]
@grantcarthew Thanks mate, I will be looking for other ways to continue helping out! :)
Cheers.

**Comment by grantcarthew** [comment]
@thomasmodeneis - Checkout the README under the documentation heading. 👍

**Comment by grantcarthew** [comment]
@thomasmodeneis - Also mate, I just changed the `test-current` test runner module so it supports arguments.

Example:

```sh

npm run tc jobOptions

```

If you leave out the argument it gives you a list of module names.

```sh


 ==============================================
   INVALID TEST NAME!
   Use one of the test names below:
 ==============================================
   enums
   is
   datetime
   dbAssertDatabase
   dbAssertTable
   dbAssertIndex
   dbAssert
   dbDriver
   dbResult
   dbReview
   job
   jobOptions
   jobParse
   jobProgress
   jobCompleted
   jobUpdate
   jobFailed
   jobLog
   queue
   queueDb
   queueState
   queueAddJob
   queueGetJob
   queueFindJob
   queueGetNextJob
   queueReanimateJob
   queueProcess
   queueChange
   queueInterruption
   queueCancelJob
   queueRemoveJob
   queueReset
   queueStop
   queueDrop
   queueSummary
 ==============================================
   Example: npm run tc jobOptions
 ==============================================
```

A little cleaner.

**Pull request merged**
